services:
  client:
    build:
      context: ./client
      args:
        NEXT_PUBLIC_API_URL: http://server:5000
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"