services:
  client:
    image: aarish96/houzez-client:latest
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    image: aarish96/houzez-server:latest
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"